#!/usr/bin/env python3
"""
export_weights.py — Convert dagger_policy.pt → policy_weights.h.

Architecture: 20 -> 64 -> 64 -> 4 MLP, no LayerNorm.
Keys in state_dict (from dagger.py PolicyNet using nn.Sequential):
    net.0.weight (64, 20), net.0.bias (64,)   — Linear 1
    net.2.weight (64, 64), net.2.bias (64,)   — Linear 2
    net.4.weight (4, 64),  net.4.bias (4,)    — Linear 3 (tanh output)

Usage:
    python export_weights.py path/to/dagger_policy.pt > src/policy_weights.h
"""
import sys, argparse
import numpy as np
import torch


def fmt_array(name, arr):
    flat = arr.reshape(-1)
    lines = [f"static const float {name}[{flat.size}] = {{"]
    for i in range(0, flat.size, 8):
        chunk = flat[i:i+8]
        lines.append("    " + ", ".join(f"{v:+.6e}f" for v in chunk) + ",")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("checkpoint")
    args = ap.parse_args()

    print(f"[loading {args.checkpoint}]", file=sys.stderr)
    sd = torch.load(args.checkpoint, map_location='cpu', weights_only=False)
    if isinstance(sd, dict) and 'state_dict' in sd:
        sd = sd['state_dict']
    elif isinstance(sd, dict) and 'model_state_dict' in sd:
        sd = sd['model_state_dict']

    # Standard PyTorch nn.Sequential naming
    keymap = {
        'W1': 'net.0.weight', 'B1': 'net.0.bias',
        'W2': 'net.2.weight', 'B2': 'net.2.bias',
        'W3': 'net.4.weight', 'B3': 'net.4.bias',
    }
    shapes = {'W1':(64,20), 'B1':(64,), 'W2':(64,64), 'B2':(64,), 'W3':(4,64), 'B3':(4,)}
    tensors = {}
    for name, key in keymap.items():
        if key not in sd:
            # try fallback search by shape
            for k, v in sd.items():
                if tuple(v.shape) == shapes[name]:
                    print(f"  [guess] {name} <- {k}", file=sys.stderr)
                    tensors[name] = v.detach().cpu().numpy().astype(np.float32)
                    break
            else:
                print(f"  [FAIL] {name} ({shapes[name]}) not found", file=sys.stderr)
                sys.exit(1)
        else:
            tensors[name] = sd[key].detach().cpu().numpy().astype(np.float32)
            print(f"  [ok] {name} <- {key} shape {tuple(tensors[name].shape)}", file=sys.stderr)

    total = sum(t.size for t in tensors.values())
    print(f"[total parameters: {total}]", file=sys.stderr)

    print(f"""/*
 * policy_weights.h
 * ----------------
 * Generated by export_weights.py from {args.checkpoint}
 * Architecture: 20 -> 64 -> 64 -> 4, no LayerNorm
 * Total parameters: {total}
 */

#ifndef POLICY_WEIGHTS_H
#define POLICY_WEIGHTS_H

""")
    for name in ['W1', 'B1', 'W2', 'B2', 'W3', 'B3']:
        print(fmt_array(name, tensors[name]))
    print("#endif /* POLICY_WEIGHTS_H */")


if __name__ == '__main__':
    main()
